server:
  servlet:
    context-path: /api/v1
  port: 8081

spring:
  application:
    name: library

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver